### ISSUE TITLE
RejectedExecutionException should be treated

### ISSUE THREAD

**Issue by lhyundeadsoul** [lhyundeadsoul/ElevatorSystem#11]
/*
Exception in thread "main" java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@55b0dcab rejected from java.util.concurrent.ThreadPoolExecutor@38afe297[Shutting down, pool size = 1, active threads = 1, queued tasks = 7, completed tasks = 0]
        at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047)
        at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823)
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1369)
        at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
        at java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:678)
        at biz.jared.domain.Dispatcher.dispatch(Dispatcher.java:53)
        at biz.jared.domain.Floor.addDirectionTask(Floor.java:80)
        at biz.jared.domain.Floor.add(Floor.java:70)
        at biz.jared.App.randomSimulate(App.java:138)
        at biz.jared.App.epoch(App.java:87)
        at biz.jared.App.main(App.java:43)
 */

**Comment by lhyundeadsoul** [comment]
## reason
* a task is submitted when the ThreadPoolExecutor is shutting down
* so, if the dispatchStrategy has a bug so that it always can't select a proper elevator, this exception may happen
## solution
* dispatchStrategy has max retry count limit
## what's my choice
this system is just a simulation system, those exception like this is not the point ... i choose stay it alone

**Comment by lhyundeadsoul** [comment]
my choice is wrong , RejectedExecutionException occurs at submit() , not the task executing. so add   a judgement like      
```   if (executorService != null && !executorService.isShutdown()) ```
is a better solution
